apiVersion: v1
kind: Service
metadata:
  name: svc-demo-deploy
spec:
  type: NodePort 
  selector: 
    app: myapp
  ports: 
    - name: http
      port: 80 #svc-ex
      targetPort: 80 #svc-int
      nodePort: 31233   
    
